repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        stages: [pre-commit]
      
      - id: ruff-format
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: python -m pytest src/backend/tests
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]